# name: CalibrationTarget
name: AT-1000ProII

hw_version: '1.0'
sw_version: '0.1'

build_settings:
  development:
    processor: 18LF57K42
    programmer: Pickit4
    defines:
      - DEVELOPMENT
      - USB_ENABLED
      - SHELL_ENABLED
      - SHELL_HISTORY_ENABLED
      - LOGGING_ENABLED

  release:
    processor: 18F26K42
    programmer: ICD-U80-win
    defines:
      # - USB_ENABLED
    
    skip_rules:
      - src/shellcommands/*
      - src/os/shell/*
      - src/os/json/*
      - src/os/judi/*
      - src/usb/*