name: AT-200ProII
hw_version: '1.0'
sw_version: '0.9.0'

build_settings:
  development:
    processor: 18LF57K42
    programmer: Pickit4
    defines:
      - DEVELOPMENT
      - USB_ENABLED
      - SHELL_ENABLED
      - SHELL_HISTORY_ENABLED
      - LOGGING_ENABLED

  release:
    processor: 18F27K42
    programmer: ICD-U80-win
    defines:
      - USB_ENABLED